server:
    port: 18005
    servlet:
        context-path: /blog
spring:
    datasource:
        #自己的阿里云服务器mysql配置
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://www.yyf256.top:3306/yyf256.blog?useUnicode=true&characterEncoding=utf8
        username: root
        password: xiaosong
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: yyf256.top.blog.entity